version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db
    env_file:
      - .env
      
  frontend:
    build: ./frontend
    ports:
      - "0.0.0.0:3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  # Development frontend service with hot reload
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "0.0.0.0:3001:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    profiles:
      - dev

volumes:
  pgdata:
